name       : perl-exporter-tiny
version    : '1.002002'
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/T/TO/TOBYINK/Exporter-Tiny-1.002002.tar.gz : 00f0b95716b18157132c6c118ded8ba31392563d19e490433e9a65382e707101
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Exporter::Tiny - an exporter with the features of Sub::Exporter but only core dependencies
description: |
    Exporter::Tiny supports many of Sub::Exporter's external-facing features including renaming imported functions with the `-as`, `-prefix` and `-suffix` options; explicit destinations with the `into` option; and alternative installers with the `installer` option. But it's written in only about 40% as many lines of code and with zero non-core dependencies.
builddeps  :
    - perl-test-fatal
    - perl-test-warnings
    - perl-try-tiny
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
