name       : perl-exporter-tiny
version    : '1.000000'
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/T/TO/TOBYINK/Exporter-Tiny-1.000000.tar.gz : ffdd77d57de099e8f64dd942ef12a00a3f4313c2531f342339eeed2d366ad078
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Exporter::Tiny - an exporter with the features of Sub::Exporter but only core dependencies
description: |
    Exporter::Tiny supports many of Sub::Exporter's external-facing features including renaming imported functions with the `-as`, `-prefix` and `-suffix` options; explicit destinations with the `into` option; and alternative installers with the `installer` option. But it's written in only about 40% as many lines of code and with zero non-core dependencies.
builddeps  :
    - perl-test-fatal
    - perl-test-warnings
    - perl-try-tiny
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
