name       : perl-exporter-tiny
version    : '1.004002'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/T/TO/TOBYINK/Exporter-Tiny-1.004002.tar.gz : 0d53898ad60e1b7dc28aeee198c4b6f454f71adefff120f016037e4974395574
homepage   : https://metacpan.org/pod/Exporter::Tiny
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Exporter::Tiny - an exporter with the features of Sub::Exporter but only core dependencies
description: |
    Exporter::Tiny supports many of Sub::Exporter's external-facing features including renaming imported functions with the `-as`, `-prefix` and `-suffix` options; explicit destinations with the `into` option; and alternative installers with the `installer` option. But it's written in only about 40% as many lines of code and with zero non-core dependencies.
builddeps  :
    - perl-test-fatal
    - perl-test-warnings
    - perl-try-tiny
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
